services:
  - type: web
    name: worldcup-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8630430801:AAEXDFGSFc3L2HNefbfHuf43gFk1-ewXQxY
      - key: TELEGRAM_CHAT_ID
        value: 500761652
